# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-budgets
  description: Terraform module to manage AWS Budgets.
  homepage: https://cloudposse.com/accelerate
  topics: ""


